### ISSUE TITLE
Norwegian transaltion

### ISSUE THREAD

**Issue by agvald** [doorkeeper-gem/doorkeeper-i18n#23]
I have created a nb.yml file with all the Norwegian translations (its nb because we have two written languages in Norway, Bokmål and Nynorsk).

How should i add it to this repo, should i just commit on master?
I tried to create a branch, when i tried to set it upstream it failed, since I don't have the rights.
Possibly someone which has rights can create a branch so i can push to it and create a pullrequest

**Comment by tute** [comment]
You can fork the repository, clone your copy, and send a pull request. See https://yangsu.github.io/pull-request-tutorial/.

Thank you!

**Comment by agvald** [comment]
yes done!
