### ISSUE TITLE
Merge PRs and create a new releasse

### ISSUE THREAD

**Issue by stoivo** [doorkeeper-gem/doorkeeper-i18n#41]
Hi, 

Is it possible to merge PRs and create a new 4.0.1 release? Last release was november 2016, over 2 years ago

**Comment by nbulaj** [comment]
Whoops, looks like I have no access to this project on rubygems :(

@tute could you please provide it using `gem owner doorkeeper-i18n --add bulajnikita@gmail.com` ?

**Comment by tute** [comment]
```
% gem owner doorkeeper-i18n --add bulajnikita@gmail.com 
Owner added successfully.
Owners for gem: doorkeeper-i18n
- nikita_bulai
- applerebel
- tutecosta@gmail.com
```

Thank you both!
