### ISSUE TITLE
v5.0.3 code will not be pushed?

### ISSUE THREAD

**Issue by yujideveloper** [doorkeeper-gem/doorkeeper-i18n#51]
Hi,

`v5.0.3` has been published at RubyGems.org.
https://rubygems.org/gems/doorkeeper-i18n/versions/5.0.3

But I can't see `v5.0.3` code at GitHub
https://github.com/doorkeeper-gem/doorkeeper-i18n/compare/v5.0.2...9c3d94ec74dc0dfdcd76e430096e5d6340d5561d

Could you push latest code with `v5.0.3` tag?

**Comment by nbulaj** [comment]
Done

https://github.com/doorkeeper-gem/doorkeeper-i18n/releases/tag/v5.0.3

**Comment by yujideveloper** [comment]
Thank you!
