### ISSUE TITLE
Please Update Gem Version

### ISSUE THREAD

**Issue by shingo-nakanishi** [doorkeeper-gem/doorkeeper-i18n#9]
I want to use the last commit(3e74c35677b0db3c54587b98e94780439fae764c).
Please Update Gem Version.

**Comment by tute** [comment]
Pushed:

* https://github.com/doorkeeper-gem/doorkeeper-i18n/releases
* https://rubygems.org/gems/doorkeeper-i18n

Thanks!

**Comment by shingo-nakanishi** [comment]
thank you.
